// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsl7ftlvQAwIz_ja27YG25Ojf9Gid_dYw',
    appId: '1:1044916763741:web:563352f74e8a9fc0c921b4',
    messagingSenderId: '1044916763741',
    projectId: 'group-planner-65c05',
    authDomain: 'group-planner-65c05.firebaseapp.com',
    storageBucket: 'group-planner-65c05.firebasestorage.app',
    measurementId: 'G-JH8Y2Y4C0F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGWdtSKCXw2ZzphuXnO3_IulQ5E8iNmN8',
    appId: '1:1044916763741:ios:78949495a77d2e8cc921b4',
    messagingSenderId: '1044916763741',
    projectId: 'group-planner-65c05',
    storageBucket: 'group-planner-65c05.firebasestorage.app',
    iosBundleId: 'com.example.groupPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsl7ftlvQAwIz_ja27YG25Ojf9Gid_dYw',
    appId: '1:1044916763741:web:019d11fb1f2d6089c921b4',
    messagingSenderId: '1044916763741',
    projectId: 'group-planner-65c05',
    authDomain: 'group-planner-65c05.firebaseapp.com',
    storageBucket: 'group-planner-65c05.firebasestorage.app',
    measurementId: 'G-ML0MND131Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWdtSKCXw2ZzphuXnO3_IulQ5E8iNmN8',
    appId: '1:1044916763741:ios:5164f87a1fbce156c921b4',
    messagingSenderId: '1044916763741',
    projectId: 'group-planner-65c05',
    storageBucket: 'group-planner-65c05.firebasestorage.app',
    iosBundleId: 'com.jmiklanek.groupplanner',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSsaxie9q81cjZuDFHS1z1Oi_BnvUT_Y',
    appId: '1:1044916763741:android:4595d7ac553a46f6c921b4',
    messagingSenderId: '1044916763741',
    projectId: 'group-planner-65c05',
    storageBucket: 'group-planner-65c05.firebasestorage.app',
  );

}